// menuData.js
// Mirrors FOOD_MENU from service_catalog.py, grouped into the same
// sections as the comments in that file. "houseSpecials" is shown by
// default in the MenuPanel; everything else appears once the guest
// taps "More".

export const MENU_SECTIONS = [
  {
    id: "houseSpecials",
    label: "House Specials",
    items: [
      { name: "Cheese Pizza", price: 349 },
      { name: "Margherita Pizza", price: 329 },
      { name: "Pepperoni Pizza", price: 399 },
      { name: "Burger", price: 199 },
      { name: "Chicken Burger", price: 249 },
      { name: "Veg Burger", price: 189 },
      { name: "Sandwich", price: 149 },
      { name: "Club Sandwich", price: 199 },
      { name: "Grilled Sandwich", price: 169 },
      { name: "Cold Coffee", price: 149 },
    ],
  },
  {
    id: "indianStarters",
    label: "Indian — Starters",
    items: [
      { name: "Paneer Tikka", price: 350 },
      { name: "Chicken Tikka", price: 380 },
      { name: "Malai Tikka", price: 400 },
      { name: "Seekh Kebab", price: 380 },
      { name: "Hara Bhara Kebab", price: 280 },
      { name: "Chicken 65", price: 320 },
      { name: "Amritsari Fish", price: 400 },
      { name: "Papdi Chaat", price: 150 },
      { name: "Samosa", price: 80 },
      { name: "Pakora", price: 120 },
    ],
  },
  {
    id: "indianMains",
    label: "Indian — Mains",
    items: [
      { name: "Butter Chicken", price: 450 },
      { name: "Chicken Tikka Masala", price: 460 },
      { name: "Dal Makhani", price: 280 },
      { name: "Dal Tadka", price: 220 },
      { name: "Paneer Butter Masala", price: 340 },
      { name: "Palak Paneer", price: 320 },
      { name: "Kadai Paneer", price: 340 },
      { name: "Shahi Paneer", price: 350 },
      { name: "Malai Kofta", price: 330 },
      { name: "Chana Masala", price: 240 },
      { name: "Rajma", price: 230 },
      { name: "Mixed Vegetable Curry", price: 260 },
      { name: "Egg Curry", price: 260 },
      { name: "Mutton Curry", price: 480 },
      { name: "Fish Curry", price: 460 },
      { name: "Prawn Curry", price: 500 },
    ],
  },
  {
    id: "riceBiryani",
    label: "Rice & Biryani",
    items: [
      { name: "Chicken Biryani", price: 380 },
      { name: "Mutton Biryani", price: 450 },
      { name: "Veg Biryani", price: 320 },
      { name: "Egg Biryani", price: 300 },
      { name: "Hyderabadi Biryani", price: 420 },
      { name: "Jeera Rice", price: 180 },
      { name: "Lemon Rice", price: 160 },
      { name: "Curd Rice", price: 150 },
      { name: "Rice", price: 120 },
      { name: "Pulao", price: 220 },
    ],
  },
  {
    id: "indoChinese",
    label: "Indo-Chinese",
    items: [
      { name: "Veg Manchurian", price: 220 },
      { name: "Gobi Manchurian", price: 220 },
      { name: "Chicken Manchurian", price: 260 },
      { name: "Chilli Paneer", price: 260 },
      { name: "Chilli Chicken", price: 280 },
    ],
  },
  {
    id: "breads",
    label: "Breads",
    items: [
      { name: "Naan", price: 60 },
      { name: "Butter Naan", price: 70 },
      { name: "Garlic Naan", price: 80 },
      { name: "Roti", price: 40 },
      { name: "Butter Roti", price: 50 },
      { name: "Tandoori Roti", price: 45 },
      { name: "Paratha", price: 60 },
      { name: "Aloo Paratha", price: 90 },
      { name: "Kulcha", price: 60 },
      { name: "Bhatura", price: 60 },
    ],
  },
  {
    id: "accompaniments",
    label: "Accompaniments",
    items: [
      { name: "Raita", price: 80 },
      { name: "Papad", price: 40 },
      { name: "Pickle", price: 30 },
      { name: "Salad", price: 220 },
    ],
  },
  {
    id: "chinese",
    label: "Chinese",
    items: [
      { name: "Veg Fried Rice", price: 220 },
      { name: "Chicken Fried Rice", price: 260 },
      { name: "Egg Fried Rice", price: 240 },
      { name: "Schezwan Fried Rice", price: 260 },
      { name: "Hakka Noodles", price: 220 },
      { name: "Chicken Noodles", price: 260 },
      { name: "Schezwan Noodles", price: 260 },
      { name: "Spring Rolls", price: 200 },
      { name: "Chicken Lollipop", price: 320 },
      { name: "Sweet Corn Soup", price: 160 },
      { name: "Hot and Sour Soup", price: 170 },
      { name: "Manchow Soup", price: 170 },
      { name: "Wonton Soup", price: 190 },
      { name: "Dim Sum", price: 280 },
      { name: "Kung Pao Chicken", price: 340 },
    ],
  },
  {
    id: "mexican",
    label: "Mexican",
    items: [
      { name: "Chicken Tacos", price: 320 },
      { name: "Veg Tacos", price: 280 },
      { name: "Chicken Burrito", price: 340 },
      { name: "Veg Burrito", price: 300 },
      { name: "Nachos", price: 280 },
      { name: "Chicken Quesadilla", price: 320 },
      { name: "Veg Quesadilla", price: 280 },
      { name: "Guacamole", price: 200 },
      { name: "Fajita", price: 350 },
      { name: "Enchiladas", price: 320 },
    ],
  },
  {
    id: "continentalItalian",
    label: "Continental & Italian",
    items: [
      { name: "Pasta Alfredo", price: 320 },
      { name: "Pasta Arrabbiata", price: 300 },
      { name: "Spaghetti Bolognese", price: 340 },
      { name: "Penne Pasta", price: 300 },
      { name: "Lasagna", price: 380 },
      { name: "Risotto", price: 360 },
      { name: "Grilled Chicken", price: 380 },
      { name: "Grilled Fish", price: 420 },
      { name: "Caesar Salad", price: 260 },
      { name: "Greek Salad", price: 240 },
      { name: "Bruschetta", price: 220 },
      { name: "Garlic Bread", price: 150 },
      { name: "Mushroom Soup", price: 180 },
      { name: "Tomato Soup", price: 160 },
    ],
  },
  {
    id: "startersGeneral",
    label: "Starters",
    items: [
      { name: "Soup", price: 180 },
      { name: "French Fries", price: 200 },
      { name: "Onion Rings", price: 180 },
    ],
  },
  {
    id: "softDrinks",
    label: "Beverages — Soft Drinks",
    items: [
      { name: "Coke", price: 80 },
      { name: "Pepsi", price: 80 },
      { name: "Sprite", price: 80 },
      { name: "Soda", price: 60 },
      { name: "Water Bottle", price: 40 },
    ],
  },
  {
    id: "juicesShakes",
    label: "Beverages — Juices & Shakes",
    items: [
      { name: "Fresh Juice", price: 150 },
      { name: "Orange Juice", price: 150 },
      { name: "Watermelon Juice", price: 130 },
      { name: "Mango Shake", price: 180 },
      { name: "Chocolate Shake", price: 190 },
      { name: "Vanilla Shake", price: 180 },
      { name: "Lassi", price: 120 },
      { name: "Buttermilk", price: 60 },
      { name: "Mocktail", price: 220 },
    ],
  },
  {
    id: "hotBeverages",
    label: "Beverages — Hot",
    items: [
      { name: "Tea", price: 60 },
      { name: "Masala Chai", price: 70 },
      { name: "Green Tea", price: 80 },
      { name: "Coffee", price: 100 },
      { name: "Cappuccino", price: 150 },
      { name: "Latte", price: 160 },
      { name: "Espresso", price: 140 },
      { name: "Hot Chocolate", price: 170 },
    ],
  },
  {
    id: "alcoholic",
    label: "Beverages — Bar",
    items: [
      { name: "Beer", price: 350 },
      { name: "Wine Glass", price: 500 },
      { name: "Whiskey Peg", price: 450 },
      { name: "Vodka Peg", price: 400 },
      { name: "Rum Peg", price: 380 },
      { name: "Cocktail", price: 450 },
    ],
  },
  {
    id: "desserts",
    label: "Desserts",
    items: [
      { name: "Gulab Jamun", price: 120 },
      { name: "Rasmalai", price: 150 },
      { name: "Jalebi", price: 100 },
      { name: "Kheer", price: 130 },
      { name: "Ice Cream", price: 180 },
      { name: "Brownie", price: 200 },
      { name: "Chocolate Cake", price: 250 },
      { name: "Cheesecake", price: 280 },
      { name: "Tiramisu", price: 300 },
      { name: "Fruit Salad", price: 150 },
      { name: "Pastry", price: 180 },
    ],
  },
];

export const HOUSE_SPECIALS_ID = "houseSpecials";